### ISSUE TITLE
Convert via modulizer for 3.0 and publish to NPM

### ISSUE THREAD

**Issue by AndreasGalster** [motss/app-datepicker#112]
It looks like modulizer will have its last few tweaks in the next 1-2 months to automatically convert all 1.x/2.x components/github repos successfully to 3.0 elements. This is just a friendly reminder that I love this element and would love to see it on NPM with a 3.0 version 😄.

For reference, 3.0 elements are in preview here and expected to be updated frequently in the next weeks to fix the last remaining issues: yarnpkg.com/en/package/@polymer/

The goal is to get 3.0 production ready in Q1 and it's looking good already.

For more info, see here: https://www.polymer-project.org/blog/2018-01-18-polymer-3-new-preview

**Comment by motss** [comment]
Thanks for the heads up 😄

**Comment by motss** [comment]
@AndreasGalster PR is totally welcome for getting the element to be Polymer 3.0 ready.

**Comment by punkratz312** [comment]
npm support would be nice. atm only the dead bower is supported.

**Comment by motss** [comment]
@punkratz312 Sorry for the delay. There are too many things going on in my life that I couldn't focus on working a new version of this element. I'd like to remove the bower since Polymer 3 has been released long while ago and I had worked on a PR that rebuilds the entire element with `LitElement` to make it a better datepicker for the community. If I got a chance to do it, I'd like the element to be written in `LitElement` but the new library yet to be stable as of the rebuilding so that has been delayed until today. This project/ element is not dead. Web Components stay strong with Firefox 63 shipped WC v1 natively for all users in current stable release.

Sorry for any inconvenience this may cause you for the existing users who are migrating to latest Polymer with NPM. Let's see how things go by the end of year 2018. Cheers. 😃

**Comment by jordanfinners** [comment]
Are you still looking for help upgrading this to Polymer 3? :)

**Comment by motss** [comment]
@jordanfinners It has been planned for `lit-element`.

**Comment by jordanfinners** [comment]
Okay @motss :) wasn't sure if you wanted me to upgrade to 3, while waiting for lit 1.0.0

**Comment by motss** [comment]
@jordanfinners I mean, why not. Feel free to submit a PR.

**Comment by jordanfinners** [comment]
Opened PR https://github.com/motss/app-datepicker/pull/125

**Comment by motss** [comment]
Fixed in #125
