### ISSUE TITLE
inputDate does not change datepicker's date value when format is not default.

### ISSUE THREAD

**Issue by madiganz** [motss/app-datepicker#116]
### Description
app-datepicker does not get update when paper input's value field changes.

### Expected outcome
date in app-datepicker gets updated normally

### Actual outcome
Nothing happens

```html
<paper-input id="input" no-label-float value="{{inputDate::input}}" on-click="_toggleCalendar"></paper-input>
<app-datepicker id="datepicker" on-click="_getDate" theme="dark-theme" format="m/d/yyyy" max-date="[[maxDate]]" disable-days="{{disableDays}}" input-date="[[inputDate]]" date="{{date}}" view="vertical" auto-update-date></app-datepicker>
```
`format="mm/dd/yyyy"` does not work either

### Browsers Affected

- [x] Chrome/ Opera
- [ ] Firefox
- [ ] Safari 10+
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge 12+
- [ ] IE 11

**Comment by madiganz** [comment]
It looks like this was originally by design? Is this something that you are interested improving?

**Comment by motss** [comment]
@madiganz Can you provide me your inputs and expected output for your case?

**Comment by madiganz** [comment]
My input would be a date = "02/25/2018" and I expect it to show this date on the map (February 25th, 2018). My format is "mm/dd/yyyy".

Did you need anything else? Not sure exactly what you are asking for.

**Comment by motss** [comment]
@madiganz Thanks. That is helpful. Will look into that shortly.

**Comment by motss** [comment]
@madiganz Had looked into this issue you encountered. Due to the limitation of the platform when comes to dealing with `Date` as you have already stated in the previous comments, `app-datepicker` only accepts dates in the format of either `yyyy/MM/dd` or `yyyy-MM-dd` from the property `inputDate` and the property `format` is only meant for formatting the selected date output by the property `date`, e.g.

```html
<app-datepicker
  format="m/d/yyyy"
  input-date="[[inputDate]]"
  date="{{selectedDate}}"></app-datepicker>
```

```js
...
const datepicker = document.querySelector('app-datepicker');

datepicker.inputDate = '2018-03-03';
datepicker.enforceDateChange(); // Imperatively update date.

console.log(datepicker.date); // 3/03/2018
...
```

Hope this clarifies the problem you're facing.

**Comment by madiganz** [comment]
Is there any reason why it can't use the format property to help with inputDate? Otherwise it is very limiting.

**Comment by motss** [comment]
@madiganz As I mentioned, due to limitation of how each browser interpret the date string, it can be unpredictable to cater for each type of date string in various format.

However, supporting multiple formats can be done but that a lot of efforts are needed in order to pull that off. Developers have to convert the date string in their supported locales to the standard format of `yyyy-MM-dd` so that `app-datepicker` will be able to understand.

**Comment by motss** [comment]
Closing this in favor of `v4`. Highly recommend using `v4` even if you are using `polymer`.

Thank you for the support.
