### ISSUE TITLE
app-datepicker seems to be broken on safari / ios-safari

### ISSUE THREAD

**Issue by gillesgw** [motss/app-datepicker#58]
Even the demo doesn't work on OSX Safari 9.0.3 with app-datepicker 2.8.1. Any clue ?

**Comment by Adesfire** [comment]
Same problem here, doens't work on Safari, see the picture attached
![safari-fail](https://cloud.githubusercontent.com/assets/13274529/24105022/0392351a-0d84-11e7-9114-9ebf7a85e2a6.JPG)

**Comment by motss** [comment]
@Adesfire what the version of the affected Safari?

**Comment by Adesfire** [comment]
Currently on Yosemite (Macbook pro) and i also tried on different iPhone (a 5 and a 6s) but they don't belongs to me and i don't know the version they are.

**Comment by motss** [comment]
@Adesfire I'm looking into the issue. I've tested it on Safari 10.0.3 on my machine and everything works just fine. Troubleshooting into your version of Safari.

**Comment by motss** [comment]
@Adesfire Tested on Safari 8.0.8 on Yosemite without any issue.
<img width="1106" alt="screen shot 2017-03-21 at 10 18 18 am" src="https://cloud.githubusercontent.com/assets/10607759/24129873/59ff1700-0e20-11e7-81a3-8add36ae4d8a.png">
<img width="1109" alt="screen shot 2017-03-21 at 10 21 17 am" src="https://cloud.githubusercontent.com/assets/10607759/24129874/5a0167bc-0e20-11e7-8865-8235eb60dfe3.png">

**Comment by Adesfire** [comment]
@motss , i don't understand why, but your demo seem to work fine indeed. 
If i create a project **from scratch** with "polymer init", then following the "Getting Started" tutorial, it work on Chorme/Edge/Firefox but still like my last capture on Safari.

Perhaps a step is missing in the "getting started" tutorial ?

Here is the code i tried in the "from scratch" test i told above : 

`<link rel="import" href="../../bower_components/polymer/polymer.html">


<link rel="import" href="../../bower_components/app-datepicker/app-datepicker.html">


// Dependencies (with or without this lines, nothing's different)
<link rel="import" href="../../bower_components/neon-animation/neon-animation.html">
<link rel="import" href="../../bower_components/paper-icon-button/paper-icon-button.html">
<link rel="import" href="../../bower_components/iron-list/iron-list.html">
<link rel="import" href="../../bower_components/iron-selector/iron-selector.html">
<link rel="import" href="../../bower_components/iron-iconset-svg/iron-iconset-svg.html">


<dom-module id="test-app">
  <template>
    <style>
      :host {
        display: block;
      }
    </style>

    <app-datepicker ></app-datepicker>

  </template>

  <script>
    Polymer({

      is: 'test-app',

      properties: {
        prop1: {
          type: String,
          value: 'test-app',
        },
      },

    });
  </script>
</dom-module>
`

**Comment by motss** [comment]
@Adesfire Make sure the components are loaded properly. Here's a [simple demo](https://jsbin.com/vucatunowu/edit?html,output).

**Comment by Adesfire** [comment]
@motss : this simple demo doesn't work on Safari (**i also try it with browserstack** on Maverick and iPhone 6S), this time nothing is displayed, 
![mac-fail](https://cloud.githubusercontent.com/assets/13274529/24140219/7f0110ae-0e1f-11e7-8c1c-a8bc0207b01a.JPG)
e nothing is displayed :

**Comment by motss** [comment]
@Adesfire It's normal as Safari does not natively support Web Components. You need to load the polyfill. The demo is intended to be tested on Chrome. You need to load Web Components polyfill. Hmm...looks like you didn't load any polyfill for Safari.

**Comment by Adesfire** [comment]
@motss Sorry for my mistake, i was thinking you build it to test the Safari browser (because your component is fine on the others). Your new demo produce the same bug as my app on my Safari 8 or browserstacker iPhone 6S & safari 7.1

![iphone-fail](https://cloud.githubusercontent.com/assets/13274529/24143521/3d40749c-0e2a-11e7-8924-a1122ac32806.JPG)
 7.1 or iPhone 6s using browserstacker, a calendar without days or heading : 
![mac-fail-2](https://cloud.githubusercontent.com/assets/13274529/24143358/b71ca250-0e29-11e7-926b-7e14be612a1b.JPG)

**Comment by motss** [comment]
@Adesfire Hmm...strange. Thank you for the screenshots. Can you help me to run this demo for a simple test https://jsbin.com/hememi/edit?html,output?

**Comment by Adesfire** [comment]
@motss : With pleasure, as you can see, when language is en-us i got an "empty" calendar, and when is in fr-fr i got nothing... Below the screenshots of Safari 8,7 & iPhone 6S
![safari-8-fr](https://cloud.githubusercontent.com/assets/13274529/24146625/c58f1ebe-0e36-11e7-8718-040e358731fe.JPG)
![safari-7](https://cloud.githubusercontent.com/assets/13274529/24146626/c59531f0-0e36-11e7-9dae-f88ff67249e2.JPG)
![safari-iphone](https://cloud.githubusercontent.com/assets/13274529/24146627/c59b9860-0e36-11e7-97b8-fa1804f0936c.JPG)

**Comment by motss** [comment]
@Adesfire I think the Intl is the culprit. Try this demo https://jsbin.com/heqojejapi/edit?html,output.

So, this datepicker element requires you to load 2 polyfills:
1. `[Web Components Polyfill](https://github.com/webcomponents/webcomponentsjs)`
2. `[Intl Polyfill](https://github.com/andyearnshaw/Intl.js/)`

To find out which version of the browsers support Intl natively, go [here](http://kangax.github.io/compat-table/esintl/).

## Why?

It is because both of the above are web platforms' features and most of the modern browsers including Safari as of version 10.x supports Intl natively when there was a very long period of time Safari is the only browser still not yet implemented Intl when IE11 and Firefox already had them for ages. And Intl basically takes care of the internationalization stuff to do basic translations and of course the locale data is going to be enormous to download to a user's browser that's why browsers should (MUST) ship this feature widely.

And as a responsible developer, I don't want my users to allow their users to download such enormous locale data just to use my datepicker (___but you can see a lot of datepicker elements out there does this which is no good___ 😢). If a browser supports the feature just use it directly at no cost.

Looking forward to your response after loading the Intl polyfill.

**Comment by Adesfire** [comment]
@motss Indeed, seem to be good now, i can see everything, some time i got problems with arrows buttons but not on your demo.

I understand your choice supporting performance, but i have to use this kind of component in a public website. So if i want to use yours, and i want it because is nice and it do many things i need for this project, i have to deal with "locales" and their heavy weight....

Many thanks for your help and for this great component, i'll post an idea in your "Any suggestions for enhancement".

**Comment by motss** [comment]
@Adesfire You can do feature detection to selectively load those polyfills so on supported browsers you don't have to send those polyfills to your users.

**Comment by motss** [comment]
Closing this issue as this unexpected outcome has been found to be Intl on Safari.
